In [ ]:
#Installing & Importing necessary libraries
import pandas as pd
import re
import json

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving battingdata2014.csv to battingdata2014.csv

In [ ]:
df_gameSummary2002 = pd.read_csv('gameSummary2002.csv')
print(df_gameSummary2002.head(10))

        Team 1       Team 2       Winner VictoryMargin        Ground  \
0    Australia        India    Australia      125 runs  Johannesburg
1        India        Kenya        India       91 runs        Durban
2    Australia    Sri Lanka    Australia       48 runs      Gqeberha
3    Australia        Kenya    Australia     5 wickets        Durban
4    Sri Lanka     Zimbabwe    Sri Lanka       74 runs   East London
5        India  New Zealand        India     7 wickets     Centurion
6        Kenya     Zimbabwe        Kenya     7 wickets  Bloemfontein
7    Australia  New Zealand    Australia       96 runs      Gqeberha
8        India    Sri Lanka        India      183 runs  Johannesburg
9  New Zealand     Zimbabwe  New Zealand     6 wickets  Bloemfontein

     Match Date          id
0  Mar 23, 2003  ODI # 1993
1  Mar 20, 2003  ODI # 1992
2  Mar 18, 2003  ODI # 1991
3  Mar 15, 2003  ODI # 1990
4  Mar 15, 2003  ODI # 1989
5  Mar 14, 2003  ODI # 1988
6  Mar 12, 2003  ODI # 1987
7  Mar 11, 2003  ODI # 1986
8  Mar 10, 2003  ODI # 1985
9   Mar 8, 2003  ODI # 1984

In [ ]:
df_gameSummary2006 = pd.read_csv('gameSummary2006.csv')
print(df_gameSummary2006.head(10))

        Team 1        Team 2        Winner VictoryMargin       Ground  \
0    Australia     Sri Lanka     Australia       53 runs   Bridgetown
1    Australia  South Africa     Australia     7 wickets   Gros Islet
2  New Zealand     Sri Lanka     Sri Lanka       81 runs     Kingston
3  West Indies       England       England      1 wicket   Bridgetown
4    Australia   New Zealand     Australia      215 runs  St George's
5  West Indies    Bangladesh   West Indies       99 runs   Bridgetown
6      Ireland     Sri Lanka     Sri Lanka     8 wickets  St George's
7      England  South Africa  South Africa     9 wickets   Bridgetown
8    Australia     Sri Lanka     Australia     7 wickets  St George's
9   Bangladesh       Ireland       Ireland       74 runs   Bridgetown

     Match Date          id
0  Apr 28, 2007  ODI # 2581
1  Apr 25, 2007  ODI # 2580
2  Apr 24, 2007  ODI # 2579
3  Apr 21, 2007  ODI # 2578
4  Apr 20, 2007  ODI # 2577
5  Apr 19, 2007  ODI # 2576
6  Apr 18, 2007  ODI # 2575
7  Apr 17, 2007  ODI # 2574
8  Apr 16, 2007  ODI # 2573
9  Apr 15, 2007  ODI # 2572

In [ ]:
df_gameSummary2010 = pd.read_csv('gameSummary2010.csv')
print(df_gameSummary2010.head(10))

        Team 1        Team 2       Winner VictoryMargin         Ground  \
0        India     Sri Lanka        India     6 wickets       Wankhede
1        India      Pakistan        India       29 runs         Mohali
2    Sri Lanka   New Zealand    Sri Lanka     5 wickets  Colombo (RPS)
3    Sri Lanka       England    Sri Lanka    10 wickets  Colombo (RPS)
4  New Zealand  South Africa  New Zealand       49 runs         Mirpur
5        India     Australia        India     5 wickets      Ahmedabad
6     Pakistan   West Indies     Pakistan    10 wickets         Mirpur
7        India   West Indies        India       80 runs        Chennai
8        Kenya      Zimbabwe     Zimbabwe      161 runs   Eden Gardens
9    Australia      Pakistan     Pakistan     4 wickets  Colombo (RPS)

     Match Date          id
0   Apr 2, 2011  ODI # 3148
1  Mar 30, 2011  ODI # 3147
2  Mar 29, 2011  ODI # 3146
3  Mar 26, 2011  ODI # 3145
4  Mar 25, 2011  ODI # 3144
5  Mar 24, 2011  ODI # 3143
6  Mar 23, 2011  ODI # 3142
7  Mar 20, 2011  ODI # 3141
8  Mar 20, 2011  ODI # 3140
9  Mar 19, 2011  ODI # 3139

In [ ]:
df_gameSummary2014 = pd.read_csv('gameSummary2014.csv')
print(df_gameSummary2014.head(10))

         Team 1        Team 2        Winner VictoryMargin      Ground  \
0     Australia   New Zealand     Australia     7 wickets   Melbourne
1     Australia         India     Australia       95 runs      Sydney
2   New Zealand  South Africa   New Zealand     4 wickets    Auckland
3   New Zealand   West Indies   New Zealand      143 runs  Wellington
4     Australia      Pakistan     Australia     6 wickets    Adelaide
5    Bangladesh         India         India      109 runs   Melbourne
6  South Africa     Sri Lanka  South Africa     9 wickets      Sydney
7       Ireland      Pakistan      Pakistan     7 wickets    Adelaide
8        U.A.E.   West Indies   West Indies     6 wickets      Napier
9     Australia      Scotland     Australia     7 wickets      Hobart

     Match Date          id
0  Mar 29, 2015  ODI # 3646
1  Mar 26, 2015  ODI # 3645
2  Mar 24, 2015  ODI # 3644
3  Mar 21, 2015  ODI # 3643
4  Mar 20, 2015  ODI # 3642
5  Mar 19, 2015  ODI # 3641
6  Mar 18, 2015  ODI # 3640
7  Mar 15, 2015  ODI # 3639
8  Mar 15, 2015  ODI # 3638
9  Mar 14, 2015  ODI # 3637

In [ ]:
df_gameSummary2019 = pd.read_csv('gameSummary2019.csv')
print(df_gameSummary2019.head(10))

        Team 1        Team 2        Winner VictoryMargin             Ground  \
0      England   New Zealand          tied             -             Lord's
1      England     Australia       England     8 wickets         Birmingham
2        India   New Zealand   New Zealand       18 runs         Manchester
3    Australia  South Africa  South Africa       10 runs         Manchester
4        India     Sri Lanka         India     7 wickets              Leeds
5   Bangladesh      Pakistan      Pakistan       94 runs             Lord's
6  Afghanistan   West Indies   West Indies       23 runs              Leeds
7      England   New Zealand       England      119 runs  Chester-le-Street
8   Bangladesh         India         India       28 runs         Birmingham
9    Sri Lanka   West Indies     Sri Lanka       23 runs  Chester-le-Street

       Match Date          id
0    Jul 14, 2019  ODI # 4192
1    Jul 11, 2019  ODI # 4191
2  Jul 9-10, 2019  ODI # 4190
3     Jul 6, 2019  ODI # 4188
4     Jul 6, 2019  ODI # 4187
5     Jul 5, 2019  ODI # 4186
6     Jul 4, 2019  ODI # 4184
7     Jul 3, 2019  ODI # 4183
8     Jul 2, 2019  ODI # 4182
9     Jul 1, 2019  ODI # 4180

In [ ]:
df_gameSummary2023 = pd.read_csv('gameSummary2023.csv')
print(df_gameSummary2023.head(10))

        Team 1        Team 2        Winner VictoryMargin        Ground  \
0        India     Australia     Australia     6 wickets     Ahmedabad
1    Australia  South Africa     Australia     3 wickets  Eden Gardens
2        India   New Zealand         India       70 runs      Wankhede
3        India   Netherlands         India      160 runs     Bengaluru
4      England      Pakistan       England       93 runs  Eden Gardens
5    Australia    Bangladesh     Australia     8 wickets          Pune
6  Afghanistan  South Africa  South Africa     5 wickets     Ahmedabad
7  New Zealand     Sri Lanka   New Zealand     5 wickets     Bengaluru
8      England   Netherlands       England      160 runs          Pune
9  Afghanistan     Australia     Australia     3 wickets      Wankhede

     Match Date          id
0  Nov 19, 2023  ODI # 4705
1  Nov 16, 2023  ODI # 4704
2  Nov 15, 2023  ODI # 4703
3  Nov 12, 2023  ODI # 4702
4  Nov 11, 2023  ODI # 4701
5  Nov 11, 2023  ODI # 4700
6  Nov 10, 2023  ODI # 4699
7   Nov 9, 2023  ODI # 4698
8   Nov 8, 2023  ODI # 4697
9   Nov 7, 2023  ODI # 4696

In [ ]:
data_mastergameSummary = pd.concat([df_gameSummary2023,df_gameSummary2019,df_gameSummary2014,df_gameSummary2010,df_gameSummary2006,df_gameSummary2002],ignore_index= True)
print(data_mastergameSummary.head(10))

        Team 1        Team 2        Winner VictoryMargin        Ground  \
0        India     Australia     Australia     6 wickets     Ahmedabad
1    Australia  South Africa     Australia     3 wickets  Eden Gardens
2        India   New Zealand         India       70 runs      Wankhede
3        India   Netherlands         India      160 runs     Bengaluru
4      England      Pakistan       England       93 runs  Eden Gardens
5    Australia    Bangladesh     Australia     8 wickets          Pune
6  Afghanistan  South Africa  South Africa     5 wickets     Ahmedabad
7  New Zealand     Sri Lanka   New Zealand     5 wickets     Bengaluru
8      England   Netherlands       England      160 runs          Pune
9  Afghanistan     Australia     Australia     3 wickets      Wankhede

     Match Date          id
0  Nov 19, 2023  ODI # 4705
1  Nov 16, 2023  ODI # 4704
2  Nov 15, 2023  ODI # 4703
3  Nov 12, 2023  ODI # 4702
4  Nov 11, 2023  ODI # 4701
5  Nov 11, 2023  ODI # 4700
6  Nov 10, 2023  ODI # 4699
7   Nov 9, 2023  ODI # 4698
8   Nov 8, 2023  ODI # 4697
9   Nov 7, 2023  ODI # 4696

In [ ]:
data_mastergameSummary.shape

(293, 7)

In [ ]:
df_battingData2002 = pd.read_csv('battingdata2002.csv')
print(df_battingData2002.head(10))

                Match Team Innings  Batting Position       Batsman Name  \
0  Australia Vs India    Australia                 1    Adam Gilchrist†
1  Australia Vs India    Australia                 2     Matthew Hayden
2  Australia Vs India    Australia                 3   Ricky Ponting(c)
3  Australia Vs India    Australia                 4      Damien Martyn
4  Australia Vs India        India                 1   Sachin Tendulkar
5  Australia Vs India        India                 2    Virender Sehwag
6  Australia Vs India        India                 3  Sourav Ganguly(c)
7  Australia Vs India        India                 4      Mohammad Kaif
8  Australia Vs India        India                 5      Rahul Dravid†
9  Australia Vs India        India                 6       Yuvraj Singh

                     Dismissal  Runs  Balls  4s  6s Strike Rate
0   c Sehwag b Harbhajan Singh    57     48   8   1      118.75
1  c †Dravid b Harbhajan Singh    37     54   5   0       68.51
2                          NaN   140    121   4   8      115.70
3                          NaN    88     84   7   1      104.76
4                c & b McGrath     4      5   1   0       80.00
5            run out (Lehmann)    82     81  10   3      101.23
6              c Lehmann b Lee    24     25   3   1       96.00
7       c †Gilchrist b McGrath     0      3   0   0        0.00
8                     b Bichel    47     57   2   0       82.45
9                 c Lee b Hogg    24     34   1   0       70.58

In [ ]:
df_battingData2006 = pd.read_csv('battingdata2006.csv')
print(df_battingData2006.head(10))

                    Match Team Innings  Batting Position  \
0  Australia Vs Sri Lanka    Australia                 1
1  Australia Vs Sri Lanka    Australia                 2
2  Australia Vs Sri Lanka    Australia                 3
3  Australia Vs Sri Lanka    Australia                 4
4  Australia Vs Sri Lanka    Australia                 5
5  Australia Vs Sri Lanka    Australia                 6
6  Australia Vs Sri Lanka    Sri Lanka                 1
7  Australia Vs Sri Lanka    Sri Lanka                 2
8  Australia Vs Sri Lanka    Sri Lanka                 3
9  Australia Vs Sri Lanka    Sri Lanka                 4

            Batsman Name                Dismissal Runs Balls  4s 6s  \
0        Adam Gilchrist†       c Silva b Fernando  149   104  13  8
1         Matthew Hayden  c Jayawardene b Malinga   38    55   3  1
2       Ricky Ponting(c)    run out (Jayawardene)   37    42   1  1
3         Andrew Symonds                      NaN   23    21   2  0
4           Shane Watson                b Malinga    3     3   0  0
5         Michael Clarke                      NaN    8     6   1  0
6          Upul Tharanga   c †Gilchrist b Bracken    6     8   1  0
7      Sanath Jayasuriya                 b Clarke   63    67   9  0
8      Kumar Sangakkara†         c Ponting b Hogg   54    52   6  1
9  Mahela Jayawardene(c)             lbw b Watson   19    19   1  0

  Strike Rate
0      143.26
1       69.09
2       88.09
3      109.52
4      100.00
5      133.33
6       75.00
7       94.02
8      103.84
9      100.00

In [ ]:
df_battingData2010 = pd.read_csv('battingdata2010.csv')
print(df_battingData2010.head(10))

                Match Team Innings  Batting Position          Batsman Name  \
0  Sri Lanka Vs India    Sri Lanka                 1         Upul Tharanga
1  Sri Lanka Vs India    Sri Lanka                 2  Tillakaratne Dilshan
2  Sri Lanka Vs India    Sri Lanka                 3  Kumar Sangakkara(c)†
3  Sri Lanka Vs India    Sri Lanka                 4    Mahela Jayawardene
4  Sri Lanka Vs India    Sri Lanka                 5    Thilan Samaraweera
5  Sri Lanka Vs India    Sri Lanka                 6    Chamara Kapugedera
6  Sri Lanka Vs India    Sri Lanka                 7      Nuwan Kulasekara
7  Sri Lanka Vs India    Sri Lanka                 8        Thisara Perera
8  Sri Lanka Vs India        India                 1       Virender Sehwag
9  Sri Lanka Vs India        India                 2      Sachin Tendulkar

                 Dismissal  Runs  Balls  4s  6s Strike Rate
0          c Sehwag b Khan     2     20   0   0       10.00
1        b Harbhajan Singh    33     49   3   0       67.34
2  c †Dhoni b Yuvraj Singh    48     67   5   0       71.64
3                      NaN   103     88  13   0      117.04
4       lbw b Yuvraj Singh    21     34   2   0       61.76
5           c Raina b Khan     1      5   0   0       20.00
6         run out (†Dhoni)    32     30   1   1      106.66
7                      NaN    22      9   3   1      244.44
8            lbw b Malinga     0      2   0   0        0.00
9  c †Sangakkara b Malinga    18     14   2   0      128.57

In [ ]:
df_battingData2014 = pd.read_csv('battingdata2014.csv')
print(df_battingData2014.head(10))

                      Match Team Innings  Batting Position  \
0  New Zealand Vs Australia  New Zealand                 1
1  New Zealand Vs Australia  New Zealand                 2
2  New Zealand Vs Australia  New Zealand                 3
3  New Zealand Vs Australia  New Zealand                 4
4  New Zealand Vs Australia  New Zealand                 5
5  New Zealand Vs Australia  New Zealand                 6
6  New Zealand Vs Australia  New Zealand                 7
7  New Zealand Vs Australia  New Zealand                 8
8  New Zealand Vs Australia  New Zealand                 9
9  New Zealand Vs Australia  New Zealand                10

          Batsman Name             Dismissal Runs Balls 4s 6s Strike Rate
0       Martin Guptill             b Maxwell   15    34  1  1       44.11
1  Brendon McCullum(c)               b Starc    0     3  0  0        0.00
2      Kane Williamson         c & b Johnson   12    33  1  0       36.36
3          Ross Taylor  c †Haddin b Faulkner   40    72  2  0       55.55
4        Grant Elliott  c †Haddin b Faulkner   83    82  7  1      101.21
5       Corey Anderson            b Faulkner    0     2  0  0        0.00
6         Luke Ronchi†      c Clarke b Starc    0     4  0  0        0.00
7       Daniel Vettori             b Johnson    9    21  1  0       42.85
8          Tim Southee     run out (Maxwell)   11    11  0  1      100.00
9           Matt Henry     c Starc b Johnson    0     7  0  0        0.00

In [ ]:
df_battingData2019 = pd.read_csv('battingdata2019.csv')
print(df_battingData2019.head(10))

                    Match Team Innings  Batting Position         Batsman Name  \
0  New Zealand Vs England  New Zealand                 1       Martin Guptill
1  New Zealand Vs England  New Zealand                 2       Henry Nicholls
2  New Zealand Vs England  New Zealand                 3   Kane Williamson(c)
3  New Zealand Vs England  New Zealand                 4          Ross Taylor
4  New Zealand Vs England  New Zealand                 5          Tom Latham†
5  New Zealand Vs England  New Zealand                 6        James Neesham
6  New Zealand Vs England  New Zealand                 7  Colin de Grandhomme
7  New Zealand Vs England  New Zealand                 8     Mitchell Santner
8  New Zealand Vs England  New Zealand                 9           Matt Henry
9  New Zealand Vs England  New Zealand                10          Trent Boult

                   Dismissal  Runs  Balls  4s  6s Strike Rate
0               lbw b Woakes    19     18   2   1      105.55
1                 b Plunkett    55     77   4   0       71.42
2      c †Buttler b Plunkett    30     53   2   0       56.60
3                 lbw b Wood    15     31   0   0       48.38
4  c sub (JM Vince) b Woakes    47     56   2   1       83.92
5          c Root b Plunkett    19     25   3   0       76.00
6  c sub (JM Vince) b Woakes    16     28   0   0       57.14
7                        NaN     5      9   0   0       55.55
8                   b Archer     4      2   1   0      200.00
9                        NaN     1      2   0   0       50.00

In [ ]:
df_battingData2023 = pd.read_csv('battingdata2023.csv')
print(df_battingData2023.head(10))

                Match Team Innings  Batting Position      Batsman Name  \
0  India Vs Australia        India                 1   Rohit Sharma(c)
1  India Vs Australia        India                 2      Shubman Gill
2  India Vs Australia        India                 3       Virat Kohli
3  India Vs Australia        India                 4      Shreyas Iyer
4  India Vs Australia        India                 5         KL Rahul†
5  India Vs Australia        India                 6   Ravindra Jadeja
6  India Vs Australia        India                 7  Suryakumar Yadav
7  India Vs Australia        India                 8    Mohammed Shami
8  India Vs Australia        India                 9    Jasprit Bumrah
9  India Vs Australia        India                10     Kuldeep Yadav

                       Dismissal Runs Balls 4s 6s Strike Rate
0               c Head b Maxwell   47    31  4  3      151.61
1                c Zampa b Starc    4     7  0  0       57.14
2                      b Cummins   54    63  4  0       85.71
3            c †Inglis b Cummins    4     3  1  0      133.33
4              c †Inglis b Starc   66   107  1  0       61.68
5          c †Inglis b Hazlewood    9    22  0  0       40.90
6          c †Inglis b Hazlewood   18    28  1  0       64.28
7              c †Inglis b Starc    6    10  1  0       60.00
8                    lbw b Zampa    1     3  0  0       33.33
9  run out (Labuschagne/Cummins)   10    18  0  0       55.55

In [ ]:
df_masterbattingData = pd.concat([df_battingData2023,df_battingData2019,df_battingData2014,df_battingData2010,df_battingData2006,df_battingData2002],ignore_index= True)

In [ ]:
print(df_masterbattingData.head(10))

                Match Team Innings  Batting Position      Batsman Name  \
0  India Vs Australia        India                 1   Rohit Sharma(c)
1  India Vs Australia        India                 2      Shubman Gill
2  India Vs Australia        India                 3       Virat Kohli
3  India Vs Australia        India                 4      Shreyas Iyer
4  India Vs Australia        India                 5         KL Rahul†
5  India Vs Australia        India                 6   Ravindra Jadeja
6  India Vs Australia        India                 7  Suryakumar Yadav
7  India Vs Australia        India                 8    Mohammed Shami
8  India Vs Australia        India                 9    Jasprit Bumrah
9  India Vs Australia        India                10     Kuldeep Yadav

                       Dismissal Runs Balls 4s 6s Strike Rate
0               c Head b Maxwell   47    31  4  3      151.61
1                c Zampa b Starc    4     7  0  0       57.14
2                      b Cummins   54    63  4  0       85.71
3            c †Inglis b Cummins    4     3  1  0      133.33
4              c †Inglis b Starc   66   107  1  0       61.68
5          c †Inglis b Hazlewood    9    22  0  0       40.90
6          c †Inglis b Hazlewood   18    28  1  0       64.28
7              c †Inglis b Starc    6    10  1  0       60.00
8                    lbw b Zampa    1     3  0  0       33.33
9  run out (Labuschagne/Cummins)   10    18  0  0       55.55

In [ ]:
df_masterbattingData.shape

(5204, 10)

In [ ]:
df_masterbattingData['Dismissal'] = df_masterbattingData['Dismissal'].apply(lambda x: 'o' if pd.notna(x) else 'n')
df_masterbattingData.rename(columns={'Dismissal': 'o/n'}, inplace=True)

df_masterbattingData.head(20)

,Match,Team Innings,Batting Position,Batsman Name,o/n,Runs,Balls,4s,6s,Strike Rate
0,India Vs Australia,India,1,Rohit Sharma(c),o,47,31,4,3,151.61
1,India Vs Australia,India,2,Shubman Gill,o,4,7,0,0,57.14
2,India Vs Australia,India,3,Virat Kohli,o,54,63,4,0,85.71
3,India Vs Australia,India,4,Shreyas Iyer,o,4,3,1,0,133.33
4,India Vs Australia,India,5,KL Rahul†,o,66,107,1,0,61.68
5,India Vs Australia,India,6,Ravindra Jadeja,o,9,22,0,0,40.90
6,India Vs Australia,India,7,Suryakumar Yadav,o,18,28,1,0,64.28
7,India Vs Australia,India,8,Mohammed Shami,o,6,10,1,0,60.00
8,India Vs Australia,India,9,Jasprit Bumrah,o,1,3,0,0,33.33
9,India Vs Australia,India,10,Kuldeep Yadav,o,10,18,0,0,55.55
10,India Vs Australia,India,11,Mohammed Siraj,n,9,8,1,0,112.50
11,India Vs Australia,Australia,1,David Warner,o,7,3,1,0,233.33
12,India Vs Australia,Australia,2,Travis Head,o,137,120,15,4,114.16
13,India Vs Australia,Australia,3,Mitchell Marsh,o,15,15,1,1,100.00
14,India Vs Australia,Australia,4,Steven Smith,o,4,9,1,0,44.44
15,India Vs Australia,Australia,5,Marnus Labuschagne,n,58,110,4,0,52.72
16,India Vs Australia,Australia,6,Glenn Maxwell,n,2,1,0,0,200.00
17,South Africa Vs Australia,South Africa,1,Quinton de Kock†,o,3,14,0,0,21.42
18,South Africa Vs Australia,South Africa,2,Temba Bavuma(c),o,0,4,0,0,0.00
19,South Africa Vs Australia,South Africa,3,Rassie van der Dussen,o,6,31,0,0,19.35

In [ ]:
print(df_masterbattingData.head(20))

                        Match  Team Innings  Batting Position  \
0          India Vs Australia         India                 1
1          India Vs Australia         India                 2
2          India Vs Australia         India                 3
3          India Vs Australia         India                 4
4          India Vs Australia         India                 5
5          India Vs Australia         India                 6
6          India Vs Australia         India                 7
7          India Vs Australia         India                 8
8          India Vs Australia         India                 9
9          India Vs Australia         India                10
10         India Vs Australia         India                11
11         India Vs Australia     Australia                 1
12         India Vs Australia     Australia                 2
13         India Vs Australia     Australia                 3
14         India Vs Australia     Australia                 4
15         India Vs Australia     Australia                 5
16         India Vs Australia     Australia                 6
17  South Africa Vs Australia  South Africa                 1
18  South Africa Vs Australia  South Africa                 2
19  South Africa Vs Australia  South Africa                 3

             Batsman Name o/n Runs Balls  4s 6s Strike Rate
0         Rohit Sharma(c)   o   47    31   4  3      151.61
1            Shubman Gill   o    4     7   0  0       57.14
2             Virat Kohli   o   54    63   4  0       85.71
3            Shreyas Iyer   o    4     3   1  0      133.33
4               KL Rahul†   o   66   107   1  0       61.68
5         Ravindra Jadeja   o    9    22   0  0       40.90
6        Suryakumar Yadav   o   18    28   1  0       64.28
7          Mohammed Shami   o    6    10   1  0       60.00
8          Jasprit Bumrah   o    1     3   0  0       33.33
9           Kuldeep Yadav   o   10    18   0  0       55.55
10         Mohammed Siraj   n    9     8   1  0      112.50
11           David Warner   o    7     3   1  0      233.33
12            Travis Head   o  137   120  15  4      114.16
13         Mitchell Marsh   o   15    15   1  1      100.00
14           Steven Smith   o    4     9   1  0       44.44
15     Marnus Labuschagne   n   58   110   4  0       52.72
16          Glenn Maxwell   n    2     1   0  0      200.00
17       Quinton de Kock†   o    3    14   0  0       21.42
18        Temba Bavuma(c)   o    0     4   0  0        0.00
19  Rassie van der Dussen   o    6    31   0  0       19.35

In [ ]:
pattern = r'\(c\)|†|\(.*?\)'
df_masterbattingData['Batsman Name'] = df_masterbattingData['Batsman Name'].str.replace(pattern, '', regex=True).str.strip()

# Display the cleaned DataFrame
df_masterbattingData.head(30)

,Match,Team Innings,Batting Position,Batsman Name,o/n,Runs,Balls,4s,6s,Strike Rate
0,India Vs Australia,India,1,Rohit Sharma,o,47,31,4,3,151.61
1,India Vs Australia,India,2,Shubman Gill,o,4,7,0,0,57.14
2,India Vs Australia,India,3,Virat Kohli,o,54,63,4,0,85.71
3,India Vs Australia,India,4,Shreyas Iyer,o,4,3,1,0,133.33
4,India Vs Australia,India,5,KL Rahul,o,66,107,1,0,61.68
5,India Vs Australia,India,6,Ravindra Jadeja,o,9,22,0,0,40.90
6,India Vs Australia,India,7,Suryakumar Yadav,o,18,28,1,0,64.28
7,India Vs Australia,India,8,Mohammed Shami,o,6,10,1,0,60.00
8,India Vs Australia,India,9,Jasprit Bumrah,o,1,3,0,0,33.33
9,India Vs Australia,India,10,Kuldeep Yadav,o,10,18,0,0,55.55
10,India Vs Australia,India,11,Mohammed Siraj,n,9,8,1,0,112.50
11,India Vs Australia,Australia,1,David Warner,o,7,3,1,0,233.33
12,India Vs Australia,Australia,2,Travis Head,o,137,120,15,4,114.16
13,India Vs Australia,Australia,3,Mitchell Marsh,o,15,15,1,1,100.00
14,India Vs Australia,Australia,4,Steven Smith,o,4,9,1,0,44.44
15,India Vs Australia,Australia,5,Marnus Labuschagne,n,58,110,4,0,52.72
16,India Vs Australia,Australia,6,Glenn Maxwell,n,2,1,0,0,200.00
17,South Africa Vs Australia,South Africa,1,Quinton de Kock,o,3,14,0,0,21.42
18,South Africa Vs Australia,South Africa,2,Temba Bavuma,o,0,4,0,0,0.00
19,South Africa Vs Australia,South Africa,3,Rassie van der Dussen,o,6,31,0,0,19.35
20,South Africa Vs Australia,South Africa,4,Aiden Markram,o,10,20,2,0,50.00
21,South Africa Vs Australia,South Africa,5,Heinrich Klaasen,o,47,48,4,2,97.91
22,South Africa Vs Australia,South Africa,6,David Miller,o,101,116,8,5,87.06
23,South Africa Vs Australia,South Africa,7,Marco Jansen,o,0,1,0,0,0.00
24,South Africa Vs Australia,South Africa,8,Gerald Coetzee,o,19,39,2,0,48.71
25,South Africa Vs Australia,South Africa,9,Keshav Maharaj,o,4,8,0,0,50.00
26,South Africa Vs Australia,South Africa,10,Kagiso Rabada,o,10,12,0,1,83.33
27,South Africa Vs Australia,South Africa,11,Tabraiz Shamsi,n,1,5,0,0,20.00
28,South Africa Vs Australia,Australia,1,Travis Head,o,62,48,9,2,129.16
29,South Africa Vs Australia,Australia,2,David Warner,o,29,18,1,4,161.11

In [ ]:
total = df_masterbattingData.isnull().sum().sort_values(ascending = False)
percent = (df_masterbattingData.isnull().sum() / df_masterbattingData.isnull().count()).sort_values(ascending = False)
missing_data = pd.concat([total, percent], axis = 1, keys = ['Total', 'Percent'])
missing_data.head(32)

                  Total  Percent
Match                 0      0.0
Team Innings          0      0.0
Batting Position      0      0.0
Batsman Name          0      0.0
o/n                   0      0.0
Runs                  0      0.0
Balls                 0      0.0
4s                    0      0.0
6s                    0      0.0
Strike Rate           0      0.0

In [ ]:
# Function to check if the teams in the Match column are in the Team 1 and Team 2 columns
def find_match_id(match):
    teams = match.split(' Vs ')
    match_id = data_mastergameSummary[
        (data_mastergameSummary['Team 1'].isin(teams) & data_mastergameSummary['Team 2'].isin(teams)) |
        (data_mastergameSummary['Team 2'].isin(teams) & data_mastergameSummary['Team 1'].isin(teams))
    ]['id']
    return match_id.iloc[0] if not match_id.empty else None

# Apply function to create a new Match id column in battingData2023
df_masterbattingData['id'] = df_masterbattingData['Match'].apply(find_match_id)

df_masterbattingData.head(20)

,Match,Team Innings,Batting Position,Batsman Name,o/n,Runs,Balls,4s,6s,Strike Rate,id
0,India Vs Australia,India,1,Rohit Sharma,o,47,31,4,3,151.61,ODI # 4705
1,India Vs Australia,India,2,Shubman Gill,o,4,7,0,0,57.14,ODI # 4705
2,India Vs Australia,India,3,Virat Kohli,o,54,63,4,0,85.71,ODI # 4705
3,India Vs Australia,India,4,Shreyas Iyer,o,4,3,1,0,133.33,ODI # 4705
4,India Vs Australia,India,5,KL Rahul,o,66,107,1,0,61.68,ODI # 4705
...,...,...,...,...,...,...,...,...,...,...,...
65,India Vs Netherlands,Netherlands,6,Bas de Leede,o,12,21,1,0,57.14,ODI # 4702
66,India Vs Netherlands,Netherlands,7,Teja Nidamanuru,o,54,39,1,6,138.46,ODI # 4702
67,India Vs Netherlands,Netherlands,8,Logan van Beek,o,16,15,2,0,106.66,ODI # 4702
68,India Vs Netherlands,Netherlands,9,Roelof van der Merwe,o,16,8,1,2,200.00,ODI # 4702
69,India Vs Netherlands,Netherlands,10,Aryan Dutt,o,5,11,0,0,45.45,ODI # 4702

In [ ]:
# Prepare the columns from match summary data for merging
game_summary_columns = data_mastergameSummary[['id', 'Winner', 'VictoryMargin', 'Ground']]

# Merge the batting summary data with the selected match summary columns on 'match_id'
merged_data = pd.merge(df_masterbattingData, game_summary_columns, on='id', how='left')
merged_data.head()

,Match,Team Innings,Batting Position,Batsman Name,o/n,Runs,Balls,4s,6s,Strike Rate,id,Winner,VictoryMargin,Ground
0,India Vs Australia,India,1,Rohit Sharma,o,47,31,4,3,151.61,ODI # 4705,Australia,6 wickets,Ahmedabad
1,India Vs Australia,India,2,Shubman Gill,o,4,7,0,0,57.14,ODI # 4705,Australia,6 wickets,Ahmedabad
2,India Vs Australia,India,3,Virat Kohli,o,54,63,4,0,85.71,ODI # 4705,Australia,6 wickets,Ahmedabad
3,India Vs Australia,India,4,Shreyas Iyer,o,4,3,1,0,133.33,ODI # 4705,Australia,6 wickets,Ahmedabad
4,India Vs Australia,India,5,KL Rahul,o,66,107,1,0,61.68,ODI # 4705,Australia,6 wickets,Ahmedabad

In [ ]:
total = merged_data.isnull().sum().sort_values(ascending = False)
percent = (merged_data.isnull().sum() / merged_data.isnull().count()).sort_values(ascending = False)
missing_data = pd.concat([total, percent], axis = 1, keys = ['Total', 'Percent'])
missing_data.head(32)

                  Total  Percent
Match                 0      0.0
Team Innings          0      0.0
Batting Position      0      0.0
Batsman Name          0      0.0
o/n                   0      0.0
Runs                  0      0.0
Balls                 0      0.0
4s                    0      0.0
6s                    0      0.0
Strike Rate           0      0.0
id                    0      0.0
Winner                0      0.0
VictoryMargin         0      0.0
Ground                0      0.0

In [ ]:
merged_data.duplicated().any()

False

In [ ]:
column_order = ['id', 'Match', 'Team Innings', 'Batting Position', 'Batsman Name', 'o/n', 'Runs', 'Balls', '4s', '6s', 'Strike Rate', 'Winner', 'VictoryMargin', 'Ground']
reordered_data = merged_data[column_order]
reordered_data.head()

,id,Match,Team Innings,Batting Position,Batsman Name,o/n,Runs,Balls,4s,6s,Strike Rate,Winner,VictoryMargin,Ground
0,ODI # 4705,India Vs Australia,India,1,Rohit Sharma,o,47,31,4,3,151.61,Australia,6 wickets,Ahmedabad
1,ODI # 4705,India Vs Australia,India,2,Shubman Gill,o,4,7,0,0,57.14,Australia,6 wickets,Ahmedabad
2,ODI # 4705,India Vs Australia,India,3,Virat Kohli,o,54,63,4,0,85.71,Australia,6 wickets,Ahmedabad
3,ODI # 4705,India Vs Australia,India,4,Shreyas Iyer,o,4,3,1,0,133.33,Australia,6 wickets,Ahmedabad
4,ODI # 4705,India Vs Australia,India,5,KL Rahul,o,66,107,1,0,61.68,Australia,6 wickets,Ahmedabad

In [ ]:
reordered_data.shape

(5204, 14)

In [ ]:
reordered_data.isnull().sum()

id                  0
Match               0
Team Innings        0
Batting Position    0
Batsman Name        0
o/n                 0
Runs                0
Balls               0
4s                  0
6s                  0
Strike Rate         0
Winner              0
VictoryMargin       0
Ground              0
dtype: int64

In [ ]:
reordered_data.to_csv('iccmaster_summary.csv',index = False)